In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np

In [2]:

FILE_NAME_21 = 'dataset_csv_file/train_subway21.csv'
FILE_NAME_22 = 'dataset_csv_file/train_subway22.csv'
FILE_NAME_23 = 'dataset_csv_file/train_subway23.csv'

train_subway21_df = pd.read_csv(FILE_NAME_21)
train_subway22_df = pd.read_csv(FILE_NAME_22)
train_subway23_df = pd.read_csv(FILE_NAME_23)

In [3]:
train_subway21_df.columns = ['TM','Line', 'station_number','station_name','Direction','STN','TA','WD','WS','RN_DAY','RN_HR1','HM','SI','ta_chi','Congestion']
train_subway22_df.columns = ['TM','Line', 'station_number','station_name','Direction','STN','TA','WD','WS','RN_DAY','RN_HR1','HM','SI','ta_chi','Congestion']
train_subway23_df.columns = ['TM','Line', 'station_number','station_name','Direction','STN','TA','WD','WS','RN_DAY','RN_HR1','HM','SI','ta_chi','Congestion']

In [4]:
train_subway_df = train_subway21_df.copy()
train_subway_df = pd.concat([train_subway_df, train_subway22_df])
train_subway_df.reset_index(inplace=True, drop=True)

train_subway_df

,TM,Line,station_number,station_name,Direction,STN,TA,WD,WS,RN_DAY,RN_HR1,HM,SI,ta_chi,Congestion
0,2021010100,1,150,서울역,상선,419,-9.6,291.1,3.3,0.0,0.0,-99.0,-99.0,-12.6,0
1,2021010101,1,150,서울역,상선,419,-9.7,284.6,2.0,0.0,0.0,-99.0,-99.0,-9.8,0
2,2021010105,1,150,서울역,상선,419,-9.3,124.7,2.4,0.0,0.0,-99.0,-99.0,-10.3,1
3,2021010106,1,150,서울역,상선,419,-9.3,126.2,1.7,0.0,0.0,-99.0,-99.0,-10.1,2
4,2021010107,1,150,서울역,상선,419,-9.1,145.7,1.3,0.0,0.0,-99.0,-99.0,-9.7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10848338,2022123119,8,2828,남위례,하선,572,-1.6,199.0,0.2,0.0,0.0,67.7,-99.0,-2.1,19
10848339,2022123120,8,2828,남위례,하선,572,-2.6,0.0,0.0,0.0,0.0,73.7,-99.0,-3.2,16
10848340,2022123121,8,2828,남위례,하선,572,-2.9,17.0,0.0,0.0,0.0,75.1,-99.0,-3.7,21
10848341,2022123122,8,2828,남위례,하선,572,-3.1,185.3,0.1,0.0,0.0,75.7,-99.0,-3.9,20
10848342,2022123123,8,2828,남위례,하선,572,-2.7,114.5,0.2,0.0,0.0,74.3,-99.0,-3.7,18

In [5]:
train_subway_df = pd.concat([train_subway_df, train_subway23_df])
train_subway_df.reset_index(inplace=True, drop=True)

train_subway_df

,TM,Line,station_number,station_name,Direction,STN,TA,WD,WS,RN_DAY,RN_HR1,HM,SI,ta_chi,Congestion
0,2021010100,1,150,서울역,상선,419,-9.6,291.1,3.3,0.0,0.0,-99.0,-99.0,-12.6,0
1,2021010101,1,150,서울역,상선,419,-9.7,284.6,2.0,0.0,0.0,-99.0,-99.0,-9.8,0
2,2021010105,1,150,서울역,상선,419,-9.3,124.7,2.4,0.0,0.0,-99.0,-99.0,-10.3,1
3,2021010106,1,150,서울역,상선,419,-9.3,126.2,1.7,0.0,0.0,-99.0,-99.0,-10.1,2
4,2021010107,1,150,서울역,상선,419,-9.1,145.7,1.3,0.0,0.0,-99.0,-99.0,-9.7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369319,2023123119,8,2828,남위례,하선,572,0.6,0.0,0.0,7.0,0.0,83.1,-99.0,0.0,18
16369320,2023123120,8,2828,남위례,하선,572,0.0,354.7,0.0,7.0,0.0,84.7,-99.0,-0.6,17
16369321,2023123121,8,2828,남위례,하선,572,-0.6,0.0,0.0,7.0,0.0,85.1,-99.0,-1.1,21
16369322,2023123122,8,2828,남위례,하선,572,-0.8,0.0,0.0,7.0,0.0,85.6,-99.0,-1.3,18
16369323,2023123123,8,2828,남위례,하선,572,-1.3,110.7,0.1,7.0,0.0,85.6,-99.0,-1.9,22

In [6]:
# 추가 결측치 반영 
# 풍향 변수 -9.9 -> 결측치

none_index = train_subway_df[train_subway_df['WD']==-9.9].index
train_subway_df.loc[none_index, 'WD'] = -99.0

In [7]:
train_subway_df[train_subway_df['WD']==-9.9]

Empty DataFrame
Columns: [TM, Line, station_number, station_name, Direction, STN, TA, WD, WS, RN_DAY, RN_HR1, HM, SI, ta_chi, Congestion]
Index: []

In [8]:
train_subway_df

,TM,Line,station_number,station_name,Direction,STN,TA,WD,WS,RN_DAY,RN_HR1,HM,SI,ta_chi,Congestion
0,2021010100,1,150,서울역,상선,419,-9.6,291.1,3.3,0.0,0.0,-99.0,-99.0,-12.6,0
1,2021010101,1,150,서울역,상선,419,-9.7,284.6,2.0,0.0,0.0,-99.0,-99.0,-9.8,0
2,2021010105,1,150,서울역,상선,419,-9.3,124.7,2.4,0.0,0.0,-99.0,-99.0,-10.3,1
3,2021010106,1,150,서울역,상선,419,-9.3,126.2,1.7,0.0,0.0,-99.0,-99.0,-10.1,2
4,2021010107,1,150,서울역,상선,419,-9.1,145.7,1.3,0.0,0.0,-99.0,-99.0,-9.7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369319,2023123119,8,2828,남위례,하선,572,0.6,0.0,0.0,7.0,0.0,83.1,-99.0,0.0,18
16369320,2023123120,8,2828,남위례,하선,572,0.0,354.7,0.0,7.0,0.0,84.7,-99.0,-0.6,17
16369321,2023123121,8,2828,남위례,하선,572,-0.6,0.0,0.0,7.0,0.0,85.1,-99.0,-1.1,21
16369322,2023123122,8,2828,남위례,하선,572,-0.8,0.0,0.0,7.0,0.0,85.6,-99.0,-1.3,18
16369323,2023123123,8,2828,남위례,하선,572,-1.3,110.7,0.1,7.0,0.0,85.6,-99.0,-1.9,22

### 결측치 처리

In [9]:
train_subway_df.isna().sum()

TM                0
Line              0
station_number    0
station_name      0
Direction         0
STN               0
TA                0
WD                0
WS                0
RN_DAY            0
RN_HR1            0
HM                0
SI                0
ta_chi            0
Congestion        0
dtype: int64

In [10]:
for column in train_subway_df.columns:

    none_index = train_subway_df[train_subway_df[column]==-99.0].index
    train_subway_df.loc[none_index, column] =  None

In [11]:
train_subway_df.isna().sum()

TM                      0
Line                    0
station_number          0
station_name            0
Direction               0
STN                     0
TA                 216468
WD                 287270
WS                 230786
RN_DAY             351574
RN_HR1             360796
HM                 844594
SI                6064242
ta_chi                352
Congestion              0
dtype: int64

### 데이터 확인

In [12]:
train_subway_df

,TM,Line,station_number,station_name,Direction,STN,TA,WD,WS,RN_DAY,RN_HR1,HM,SI,ta_chi,Congestion
0,2021010100,1,150,서울역,상선,419,-9.6,291.1,3.3,0.0,0.0,NaN,NaN,-12.6,0
1,2021010101,1,150,서울역,상선,419,-9.7,284.6,2.0,0.0,0.0,NaN,NaN,-9.8,0
2,2021010105,1,150,서울역,상선,419,-9.3,124.7,2.4,0.0,0.0,NaN,NaN,-10.3,1
3,2021010106,1,150,서울역,상선,419,-9.3,126.2,1.7,0.0,0.0,NaN,NaN,-10.1,2
4,2021010107,1,150,서울역,상선,419,-9.1,145.7,1.3,0.0,0.0,NaN,NaN,-9.7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16369319,2023123119,8,2828,남위례,하선,572,0.6,0.0,0.0,7.0,0.0,83.1,NaN,0.0,18
16369320,2023123120,8,2828,남위례,하선,572,0.0,354.7,0.0,7.0,0.0,84.7,NaN,-0.6,17
16369321,2023123121,8,2828,남위례,하선,572,-0.6,0.0,0.0,7.0,0.0,85.1,NaN,-1.1,21
16369322,2023123122,8,2828,남위례,하선,572,-0.8,0.0,0.0,7.0,0.0,85.6,NaN,-1.3,18
16369323,2023123123,8,2828,남위례,하선,572,-1.3,110.7,0.1,7.0,0.0,85.6,NaN,-1.9,22

1. 결측치 제거 후 이상치 확인

In [13]:
train_subway_dropna_df = train_subway_df.dropna()
train_subway_dropna_df.isna().sum()

TM                0
Line              0
station_number    0
station_name      0
Direction         0
STN               0
TA                0
WD                0
WS                0
RN_DAY            0
RN_HR1            0
HM                0
SI                0
ta_chi            0
Congestion        0
dtype: int64

In [14]:
train_subway_df.isna().sum()

TM                      0
Line                    0
station_number          0
station_name            0
Direction               0
STN                     0
TA                 216468
WD                 287270
WS                 230786
RN_DAY             351574
RN_HR1             360796
HM                 844594
SI                6064242
ta_chi                352
Congestion              0
dtype: int64

Congestion 추가 이상치 확인

In [15]:
# 남위례 Congestion 0 제거 

zero_index =train_subway_dropna_df[(train_subway_dropna_df['station_name']=='남위례') & (train_subway_dropna_df['Congestion']==0)].index
train_subway_dropna_0_df = train_subway_dropna_df.drop(zero_index)
train_subway_dropna_0_df.reset_index(inplace=True, drop=True)
train_subway_dropna_0_df

,TM,Line,station_number,station_name,Direction,STN,TA,WD,WS,RN_DAY,RN_HR1,HM,SI,ta_chi,Congestion
0,2021072220,1,150,서울역,상선,419,30.6,288.1,0.7,0.0,0.0,54.3,0.08,30.2,10
1,2021072306,1,150,서울역,상선,419,25.8,168.7,0.8,0.0,0.0,73.5,0.02,27.2,14
2,2021072307,1,150,서울역,상선,419,27.0,156.9,1.5,0.0,0.0,71.7,0.40,28.4,32
3,2021072308,1,150,서울역,상선,419,27.7,162.1,1.6,0.0,0.0,67.1,0.99,30.0,48
4,2021072309,1,150,서울역,상선,419,28.1,145.6,2.0,0.0,0.0,65.9,1.71,31.1,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9594131,2023123114,8,2828,남위례,하선,572,3.0,306.0,1.1,7.0,0.0,75.8,0.18,2.7,13
9594132,2023123115,8,2828,남위례,하선,572,3.7,24.7,1.2,7.0,0.0,73.0,0.65,3.5,14
9594133,2023123116,8,2828,남위례,하선,572,4.2,7.0,0.7,7.0,0.0,71.5,0.66,3.8,16
9594134,2023123117,8,2828,남위례,하선,572,3.7,303.4,0.2,7.0,0.0,72.6,0.26,3.4,19
9594135,2023123118,8,2828,남위례,하선,572,2.1,0.0,0.0,7.0,0.0,77.4,0.03,1.6,18

### 데이터 전처리

In [16]:
train_subway_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16369324 entries, 0 to 16369323
Data columns (total 15 columns):
 #   Column          Dtype
---  ------          -----
 0   TM              int64
 1   Line            int64
 2   station_number  int64
 3   station_name    object
 4   Direction       object
 5   STN             int64
 6   TA              float64
 7   WD              float64
 8   WS              float64
 9   RN_DAY          float64
 10  RN_HR1          float64
 11  HM              float64
 12  SI              float64
 13  ta_chi          float64
 14  Congestion      int64
dtypes: float64(8), int64(5), object(2)
memory usage: 1.8+ GB

### feature, target 선택

In [ ]:
feature_df = train_subway_dropna_0_df.loc[:,['STN','WD','WS','RN_DAY','RN_HR1','HM','SI','ta_chi']]
target_sr = train_subway_dropna_0_df['Congestion']

print(feature_df.shape, target_sr.shape)

(9594136, 8) (9594136,)

In [18]:
feature_df.head(5)

   STN     WD   WS  RN_DAY  RN_HR1    HM    SI  ta_chi
0  419  288.1  0.7     0.0     0.0  54.3  0.08    30.2
1  419  168.7  0.8     0.0     0.0  73.5  0.02    27.2
2  419  156.9  1.5     0.0     0.0  71.7  0.40    28.4
3  419  162.1  1.6     0.0     0.0  67.1  0.99    30.0
4  419  145.6  2.0     0.0     0.0  65.9  1.71    31.1

In [19]:
target_sr.head(5)

0    10
1    14
2    32
3    48
4    34
Name: Congestion, dtype: int64

### test, train 분리

In [20]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(feature_df, target_sr, test_size=0.2, random_state=33)

In [21]:
print(f'x_train : {x_train.shape}, y_train : {y_train.shape}')
print(f'x_test : {x_test.shape} , y_test : {y_test.shape}')

x_train : (7675308, 8), y_train : (7675308,)
x_test : (1918828, 8) , y_test : (1918828,)

스케일링

In [ ]:
# # feature 스케일링 
# # StandardScaler 사용 

# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

# x_train_scaled = scaler.fit_transform(x_train)
# x_train_scaled = pd.DataFrame(x_train_scaled, columns=x_train.columns)

# x_test_scaled = scaler.transform(x_test)
# x_test_scaled = pd.DataFrame(x_test_scaled, columns=x_test.columns)

In [ ]:
# feature 스케일링 
# MinMaxScaler 사용 

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_train_scaled = pd.DataFrame(x_train_scaled, columns=x_train.columns)

x_test_scaled = scaler.transform(x_test)
x_test_scaled = pd.DataFrame(x_test_scaled, columns=x_test.columns)

In [24]:
print(x_train_scaled.shape, x_test_scaled.shape)

(7675308, 8) (1918828, 8)

### 모델 학습 및 훈련

In [25]:
from lightgbm import LGBMRegressor

In [26]:
lgbm_model = LGBMRegressor(n_estimators=1000, learning_rate = 0.1, device='gpu')
lgbm_model.fit(x_train_scaled, y_train)

[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1562
[LightGBM] [Info] Number of data points in the train set: 7675308, number of used features: 8
[LightGBM] [Info] Using GPU Device: NVIDIA GeForce GTX 1650 with Max-Q Design, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 6 dense feature groups (58.56 MB) transferred to GPU in 0.164253 secs. 1 sparse feature groups
[LightGBM] [Info] Start training from score 26.104286

LGBMRegressor(device='gpu', n_estimators=1000)

In [28]:
from sklearn.metrics import mean_squared_error, r2_score

# GPU 기반 예측
y_train_pred = lgbm_model.predict(x_train_scaled)
y_test_pred = lgbm_model.predict(x_test_scaled)


train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))

train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_test_pred)

print(f"Train RMSE: {train_rmse:.4f}, Test RMSE : {test_rmse:.4f}")
print(f"Train R²: {train_r2:.4f}, Test R² : {test_r2:.4f}")

Train RMSE: 16.5779, Test RMSE : 16.6494
Train R²: 0.3207, Test R² : 0.3175